export const materias = [
    {
        id: 1,
        slug:"Compre-o-novo-Galaxy-S26-Ultra-no-Magalu-e-ganhe-mais-de-100-mil-pontos-Livelo",
        data: "26/02/2026",
        titulo: "Compre o novo Galaxy S26 Ultra no Magalu e ganhe mais de 100 mil pontos Livelo",
        subtitulo: "Alerta de oportunidade para quem está pensando em trocar de celular",
        materia: "Alerta de oportunidade para quem está pensando em trocar de celular 📱A Livelo está oferecendo 10 pontos por real gasto no Magalu nas compras da linha dos novos Galaxy S26. Com a oferta, é possível ganhar até 100 mil pontos Livelo, com a compra do Galaxy S26 Ultra. A oferta é válida até o domingo (1), confira na matéria!",
        autor: "Roberto Bodetti",
        categoria: "Noticias",
        imagem: "https://passageirodeprimeira.com/wp-content/uploads/2026/02/compre-o-novo-galaxy-s26-ultra-no-magalu-e-ganhe-mais-de-100-mil-pontos-livelo-capa-livelo-galaxy.png",
    },

    {
        id: 2,
        slug: "Comissao-do-Senado-aprova-prova-obrigatoria-para-novos-medicos",
        data: "26/02/2026",
        titulo: "Comissão do Senado aprova prova obrigatória para novos médicos",
        subtitulo: "Texto segue para análise na Câmara dos Deputados.",
        materia: "A Comissão de Assuntos Sociais (CAS) do Senado aprovou, nessa quarta-feira (25), o projeto de lei que torna obrigatório um exame de proficiência para o exercício da Medicina . O texto segue para análise na Câmara dos Deputados.",
        autor: "Marcelo Camargo",
        categoria: "Noticias",
        imagem: "https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3745908:1772100348/M%C3%A9dico.webp",
    },
    {
        id: 3,
        slug: "Aparelho-automatizado-do-Ciscopar-agiliza-testes-de-tuberculose",
        data: "27/02/2026",
        titulo: "Aparelho automatizado do Ciscopar agiliza testes de tuberculose",
        subtitulo: "",
        materia: "A recente aquisição de um equipamento automatizado de Teste Rápido Molecular da Tuberculose (TRM) no Ciscopar representa um passo importante e inovador na luta contra essa doença na região Oeste. Esse aparelho permite a detecção da bactéria que causa a tuberculose em menos de duas horas, reduzindo significativamente o tempo de diagnóstico. Esse tipo de inovação tecnológica contribui diretamente para a melhoria dos serviços de saúde pública, promovendo um enfrentamento mais eficaz da tuberculose, um problema de saúde que ainda afeta milhares de famílias no Brasil.",
        autor: "Jornal do Oeste",
        categoria: "Noticias",
        imagem: "https://media.jornaldooeste.com.br/2026/02/96eed5c5-teste_tuberculose-1-750x430.jpg",
    },

    {
        id: 5,
        slug: "",
        data: "27/02/2026",
        titulo: "Astronomos-descobrem-nova-superterra-a-91-anos-luz-da-Terra",
        subtitulo: "Planeta HD 176986 d tem massa até sete vezes maior e orbita estrela anã laranja do tipo K",
        materia: "Uma equipe internacional de astrônomos identificou um novo planeta do tipo superterra orbitando a estrela HD 176986, localizada a cerca de 91 anos‑luz da Terra — um ano-luz equivale a cerca de 9,46 trilhões de quilômetros. A descoberta foi liderada pelo Instituto de Astrofísica das Ilhas Canárias (IAC) e publicada na revista Astronomy & Astrophysics, ampliando para três o número de planetas conhecidos no sistema. A estrela, uma anã laranja do tipo K ligeiramente menor que o Sol, já era conhecida por abrigar dois planetas desde 2018. Desde então, a equipe acompanhou o sistema até que o sinal do terceiro planeta enfim se destacasse das medições.",
        autor: "O Globo",
        categoria: "Noticias",
        imagem: "https://s2-oglobo.glbimg.com/AabWq94bkwYYh-eprx03x17ZTRM=/0x0:3840x2160/888x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2025/6/e/PTxdphTqSA9el0JiErRA/pexels-zelch-30596254.jpg",
    },
    {
        id: 6,
        slug: "Artemis-2-Nasa-recolhe-foguete-para-reparos-e-atrasa-missao-tripulada-a-Lua",
        data: "21/02/2026",
        titulo: "Artemis 2: Nasa recolhe foguete para reparos e atrasa missão tripulada à Lua",
        subtitulo: "Foguete SLS, da missão Artemis 2, vai ser levado de volta ao hangar para manutenção",
        materia: "A Nasa realiza nesta quarta-feira (25) a transferência de seu imponente foguete lunar SLS para seu hangar para reparos, depois que problemas técnicos levaram ao adiamento da decolagem da primeira missão tripulada de sobrevoo à Lua em mais de 50 anos. A agência espacial americana informou que retiraria da plataforma de lançamento em Cabo Canaveral, Flórida, seu foguete SLS de 98 metros após as equipes detectarem falhas no fluxo de hélio. A decisão implica novos atrasos para a muito aguardada missão Artemis 2, que durará aproximadamente 10 dias e levará três americanos e um canadense a voar ao redor do satélite terrestre",
        autor: "AFP",
        categoria: "Noticias",
        imagem: "https://conteudo.imguol.com.br/c/noticias/a8/2026/02/23/foguete-sls-da-missao-artemis-2-da-nasa-em-estacao-de-lancamento-no-centro-espacial-kennedy-em-cabo-canaveral-na-florida-eua-1771855456877_v2_900x506.jpg",
    },
    {
        id: 7,
        slug: "Resident-Evil-Requiem-TALEVINHO-NO-PC!",
        data: "27/02/2026",
        titulo: "Resident Evil Requiem TÁ LEVINHO NO PC!",
        subtitulo: "Descubra aqui se o novo Resident Evil vai rodar no seu PC!",
        materia: "O lançamento do novo Resident Evil Requiem está chegando, e a maior dúvida da comunidade PC gamer é: o jogo vai rodar no meu “PC baratinho”? Se você está preocupado com os requisitos e não sabe se sua máquina vai aguentar, temos ótimas notícias! Testamos o desempenho do jogo em diferentes hardwares de entrada e o veredito é claro: a RE Engine continua fazendo milagres em otimização. Abaixo, detalhamos como o jogo se comportou na popular RX 6600, na guerreira GTX 1060 e até mesmo nos consoles portáteis como o Steam Deck. E pode ficar tranquilo: este post é totalmente livre de spoilers da história",
        autor: "Adrenaline",
        categoria: "Noticias",
        imagem: "https://www.adrenaline.com.br/wp-content/uploads/2025/12/Resident-Evil-Requiem-Gameplay-Leon-Grace.jpg",
    },
    {
        id: 8,
        slug: "Como-a-taxacao-de-bets-virou-entrave-no-PL-Antifaccao",
        data: "25/02/2026",
        titulo: "Como a taxação de bets virou entrave no PL Antifacção",
        subtitulo: "Câmara dos Deputados aprova projeto de lei sem tributação de apostas online",
        materia: "A Câmara dos Deputados aprovou na terça-feira (24) o PL Antifacção (PL 5.582/2025), marco legal de combate ao crime organizado. O texto retirou a maior parte das emendas adicionadas pelo Senado e se manteve semelhante à proposta aprovada pelos deputados em novembro de 2025, sob a relatoria de Guilherme Derrite (PP-SP). Um dos pontos retirados pela Câmara foi a taxação das bets, que previa a destinação dos tributos para o Fundo Nacional de Segurança Pública e o combate ao crime organizado. Os deputados que votaram pela retirada argumentaram que esse debate deveria ocorrer de maneira separada e que uma proposta semelhante de tributação das apostas esportivas foi aprovada em dezembro de 2025.",
        autor: "Lucas Zacari",
        categoria: "Noticias",
        imagem: "https://nexo-uploads-beta.s3.amazonaws.com/wp-content/uploads/images/2026/02/img20260225004154449-1-scaled.webp",
    },
    {
        id: 9,
        slug: "Como-a-presenca-LGBTI-mudou-nas-telenovelas",
        data: "25/02/2026",
        titulo: "Como a presença LGBTI+ mudou nas telenovelas",
        subtitulo: "Casal ‘Loquinha’, de ‘Três graças’, tornou-se fenômeno nas redes sociais.",
        materia: "O casal Lorena (Alanis Guillen) e Juquinha (Gabriela Medvedovsky), da novela “Três graças”, da TV Globo, teve a sua primeira relação sexual apresentada na terça-feira (24), após um pedido de casamento. No X, o assunto “Primeira vez Loquinha” era o quinto mais comentado na quarta-feira (25). Relações de casais LGBTI+ nem sempre receberam tanta visibilidade, ou foram tão bem aceitas pelo público. Os personagens eram representados de maneira caricata e seus relacionamentos muitas vezes acabavam, ou perdiam espaço nas novelas, por reclamações de telespectadores.",
        autor: "Giovanna Castro",
        categoria: "Noticias",
        imagem: "https://nexo-uploads-beta.s3.amazonaws.com/wp-content/uploads/images/2026/02/Design-sem-nome-_30_-600x374.webp",
    },
    {
        id: 10,
        slug: "A-forca-do-lobby-para-frear-os-impostos-de-refrigerantes",
        data: "22/02/2026",
        titulo: "A força do lobby para frear os impostos de refrigerantes",
        subtitulo: "Levantamento da Agência Pública mostra que a maior parte dessas bebidas, que deveriam ter o consumo desestimulado de acordo com a legislação, se encaminha para pagar menos tributos que a água mineral",
        materia: "Com exceção de quem produz e de quem consome, há certo consenso no meio científico de que a ingestão excessiva de refrigerantes promove danos à saúde. É com base nesse pensamento voltado à saúde pública que as bebidas açucaradas foram incluídas no rol de produtos que passarão a pagar o Imposto Seletivo (IS), o popular “imposto do pecado”, após a reforma tributária em 2024. A premissa da taxa parece simples: aumentar os impostos (e, consequentemente, o valor de venda) de produtos nocivos à saúde ou ao meio ambiente para desestimular seu consumo. É o caminho que muitos países vêm adotando e foi uma das conquistas da reforma, que, sem acordo, foi protelada por quase três décadas até ganhar uma versão desidratada aprovada no Congresso Nacional. Um relatório divulgado pela Organização Mundial da Saúde (OMS), em 13 de janeiro deste ano, com dados globais até 2024, coloca o Brasil entre os países que justamente não conseguiram reduzir o consumo de produtos açucarados nocivos à saúde. Apenas 28% das nações avançaram nesse caminho. O documento critica países que usam impostos apenas para arrecadação, sem vinculá-los a políticas de saúde pública. É justamente essa lógica que a Reforma Tributária tem a chance de mudar.",
        autor: "Ed Wanderley",
        categoria: "Noticias",
        imagem: "https://nexo-uploads-beta.s3.amazonaws.com/wp-content/uploads/images/2026/02/refrigerantes-1.webp",
    },
    {
        id: 11,
        slug: "",
        data: "12/07/2023",
        titulo: "Como-tirar-mancha-de-cafe-da-roupa",
        subtitulo: "Como tirar mancha de café da roupa? A gente te ensina a tirar mancha da roupa sem danificar sua peça! Confira dicas para o dia a dia no Blog Compra Certa!",
        materia: "O café faz parte da rotina do povo brasileiro, isso não podemos negar. A qualquer hora do dia um cafezinho é sempre bem-vindo, seja para começar o dia, após o almoço, no lanche da tarde ou quando estamos precisando de uma dose de ânimo para enfrentar o dia. Além disso, também utilizamos muito o café para preparar receitas deliciosas como a de cappucino e tiramisù. Uma bebida muito versátil e cheia de sabor, não é mesmo? Com toda essa presença do café no dia a dia, é comum que pequenos acidentes ocorram e caia um pouco de café na roupa. E agora, como tirar mancha de café da roupa sem danificar o tecido? Nós vamos te ajudar a resolver essa questão sem danificar suas roupas e toalhas de mesa! Na matéria você vai encontrar:– Dicas de como tirar mancha de café– Como tirar mancha de café seca– Como tirar mancha de café em roupa branca",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/1UPDiP8RTMpCikf1ucuthy/b4f18ce416992bdc5509f74480168f3d/Blog-artigo-1.webp",
    },
    {
        id: 12,
        slug: "Lista-de-compras-de-supermercado-dicas-de-ouro-para-fazer-a-sua",
        data: "01/09/2022",
        titulo: "Lista de compras de supermercado: dicas de ouro para fazer a sua",
        subtitulo: "Preparar uma lista de compras de supermercado é algo que poderia ser feito com mais frequência.",
        materia: "Preparar uma lista de compras de supermercado é algo que poderia ser feito com mais frequência. Geralmente, apenas “anotamos mentalmente” o que precisamos e, por conta disso, acabamos esquecendo algo ou até comprando mais do que precisávamos. Mas isso acaba hoje! Para facilitar essa missão, além de ajudar você a controlar melhor seus gastos, economizar tempo e ser mais eficiente nessa tarefa, preparamos este conteúdo especial. Venha com a gente conferir algumas dicas simples e muito eficientes para fazer uma lista de compras perfeita.",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/7FLgEAHNmRNxQwFeLV03eA/d361016ef3f3dafd0d1d6131ae69c666/CC_IMAGENS_CONTEUDO_BLOG_775x400-11-1.webp",
    },
    {
        id: 13,
        slug: "Como-limpar-maquina-de-lavar-louca",
        data: "27/02/2026",
        titulo: "Como limpar máquina de lavar louça?",
        subtitulo: "Dicas de como limpar máquina de lavar louça: sua máquina com ótimo funcionamento, sem odores e uma rotina muito mais prática.",
        materia: "Alguns eletrodomésticos facilitam nossa rotina, otimizam nosso tempo e nos ajudam a fazer algumas tarefas domésticas de forma mais rápida e prática. É o caso da lava louças. Além da praticidade, ela nos faz economizar água e entrega nossas louças limpinhas e brilhantes. Mas, você já parou para pensar que a lava louça também precisa ser higienizada da forma certa? Agora você vai aprender como limpar máquina de lavar louça e manter o bom funcionamento dela.",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/3hjzMNN2OWqJWRYvS2F6uf/95246cc8539c69762080f556b0018b1a/3-1-400x225.png",
    },
    {
        id: 14,
        slug: "Simbolos-de-lavagem-de-roupas-voce-sabe-interpretar",
        data: "27/02/2026",
        titulo: "Símbolos de lavagem de roupas: você sabe interpretar?",
        subtitulo: "Sabe lavar suas roupas sem danificá-las? O Blog Compra Certa te ensina a ler os símbolos de lavagem de roupas pra não cometer erros! Vem conferir essa dica!",
        materia: "Provavelmente já aconteceu com você pelo menos uma vez: manchar uma peça de roupa na máquina de lavar roupas, ter uma roupa encolhida na secadora de roupas ou até mesmo ter alguma peça que danificou o tecido durante ou depois de lavar. Você sabia que isso pode ser evitado se você souber interpretar o significado entender o que significam dos símbolos de lavagem de roupas? Repare bem na etiqueta de suas roupas: é bem comum encontrar nelas alguns desenhos que podem parecer estranhos e talvez você não saiba seus significados. Mas nós vamos te ajudar a entendê-los e a partir de agora você saberá como cuidar das suas roupas corretamente.",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/Fya3RIWxVrvRRBpqdRJMP/cdaedb6f258ce7e74d989de00ab41796/Destaque-simbolos-de-lavagem.png",
    },
    {
        id: 15,
        slug: "Cooktop-para-espacos-pequenos-como-aproveitar-cada-centimetro-da-cozinha",
        data: "27/02/2026",
        titulo: "Cooktop para espaços pequenos: como aproveitar cada centímetro da cozinha",
        subtitulo: "Cozinhar é uma arte. Mas só quem mora em uma casa ou apartamento compacto sabe o que é fazer mágica para preparar qualquer prato.",
        materia: "Cozinhar é uma arte. Mas só quem mora em uma casa ou apartamento compacto sabe o que é fazer mágica para preparar qualquer prato. Duvida? A tábua com os temperos precisa dividir espaço com o escorredor, os bowls ocupam metade da bancada, e ainda falta lugar para a louça. Bom, é por isso que o cooktop virou o melhor amigo das cozinhas modernas e integradas. Afinal de contas, ele é discreto, bonito e, se for bem planejado, ainda ajuda a liberar área preciosa da bancada — algo que, em espaços reduzidos, vale ouro. Mas aí surge a dúvida: qual modelo se adapta melhor para cada caso? E como escolher o cooktop para sua cozinha pequena? Um cooktop pequeno, mas potente? Um modelo de indução que une tecnologia e segurança? Ou aquele equipamento 4 bocas megacompacto que dá conta de tudo e ocupa pouco espaço? Para resolver essas questões, hoje o nosso blog vai te ajudar a pensar exatamente sobre isso: vamos conversar sobre como escolher o cooktop para espaços pequenos, quais são as opções ideais para o seu estilo de vida, com dicas de medidas, instalação e truques que realmente fazem diferença na rotina. Preparado? Então, puxe a cadeira — ou melhor, o banquinho da ilha — e venha descobrir como transformar pouco espaço em muito sabor.",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/2fmdTjIzATRf9mFGr3HrBH/50ba147b42c47e94c37dfb379e07ef8f/shutterstock_2525470943.jpg",
    },
    {
        id: 16,
        slug: "Fogao-Geladeira-ou-Lava-e-Seca-qual-comprar-na-Black-Friday",
        data: "27/02/2026",
        titulo: "Fogão, Geladeira ou Lava e Seca: qual comprar na Black Friday?",
        subtitulo: "Todo ano é a mesma coisa: chega a Black Friday e a gente começa a imaginar como seria trocar aquele eletrodoméstico que vive pedindo paciência.",
        materia: "Todo ano é a mesma coisa: chega a Black Friday e a gente começa a imaginar como seria trocar aquele eletrodoméstico que vive pedindo paciência. A geladeira que está fazendo um barulhão, o fogão cansado, a roupa demorando uma eternidade para secar… e, no fim, surge a mesma pergunta de sempre: o que comprar primeiro? Se esse é seu caso, já saiba que não é só você que passa por isso, viu? É natural ficar dividido entre o que precisa agora e o que seria ótimo ter em casa, ainda mais em tempos com tantas opções... Então, vamos direto ao que interessa porque hoje é dia de te ajudar a entender de vez o que realmente faz diferença no seu dia a dia. Isso mesmo: se prepare que nosso blog, a partir de agora, vai te ajudar a mergulhar no melhor dos eletrodomésticos na Black Friday, mostrando tudo que você precisa para renovar sua casa com confiança, economia e tranquilidade. Preparado? Vem com a gente.",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/67MeuHrW5Rv5BBFT9fftAx/21eb22182aa2859c46e04a6d5fd8cd14/shutterstock_2627344935.jpg",
    },
    {
        id: 17,
        slug: "Outlet-Compra-Certa-entenda-as-diferencas-e-como-economizar",
        data: "27/02/2026",
        titulo: "Outlet Compra Certa: entenda as diferenças e como economizar",
        subtitulo: "Renovar a casa ou montar o primeiro lar é uma jornada cheia de planos.",
        materia: "Renovar a casa ou montar o primeiro lar é uma jornada cheia de planos. Você pensa no fogão que vai usar diariamente, na geladeira que precisa ser prática, na máquina de lavar que vai facilitar a rotina. Só que existe um ponto que sempre entra no radar: como escolher bem sem comprometer o orçamento? É aí que muita gente descobre, às vezes, até por acaso, que o outlet e eletrodomésticos seminovos podem ser exatamente a solução para conseguir tudo isso e pagando menos. Se esse é seu caso, então bora com a gente porque hoje nosso blog vai mergulhar no universo Compra Certa e mostrar tudo sobre o que é nosso outlet, como explorar com tranquilidade a área de produtos seminovos, como funciona a garantia para sua casa e, lógico, quando cada tipo de produto é a melhor escolha para você. Preparado para entender a melhor forma de economizar e ainda escolher um produto confiável?",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/223q0HaHCpNqV8QylL3NUN/a5c5bfbe4534e678b6a7790dce1c2225/shutterstock_2586913583.jpg",
    },
    {
        id: 18,
        slug: "Maquina-de-lavar-qual-e-a-capacidade-ideal-para-sua-casa",
        data: "27/02/2026",
        titulo: "Máquina de lavar: qual é a capacidade ideal para sua casa",
        subtitulo: "Você já parou para pensar que escolher a máquina de lavar ideal é quase como encontrar um parceiro de rotina?",
        materia: "Você já parou para pensar que escolher a máquina de lavar ideal é quase como encontrar um parceiro de rotina? Ela precisa acompanhar seu ritmo, entender o tamanho da sua família e, claro, dar conta de todo o volume de roupa — sem desperdiçar água, energia ou sabão. E como cada casa tem seu próprio jeito, vale entender bem o que muda entre as lavadoras de 9 kg, 12 kg e 14 kg ou mais. Assim, você escolhe o modelo certo, otimiza o uso e ainda economiza em cada ciclo. Vamos juntos entender qual máquina combina com o seu dia a dia?",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/2YZogySgIbGfZZKV3wprUl/d50148cc81bfa3c23630baf86a80fbb7/shutterstock_2556968761.jpg",
    },
    {
        id: 19,
        slug: "Freezer-Vertical-ou-Horizontal-qual-combina-com-o-seu-dia-a-dia",
        data: "27/02/2026",
        titulo: "Freezer Vertical ou Horizontal: qual combina com o seu dia a dia?",
        subtitulo: "Imagina a cena: você está planejando uma festa, o fim de semana daquele churrasco com os amigos ou quer simplesmente estocar as marmitas da semana em paz e, do nada, percebe que o freezer da geladeira já não dá conta do recado.",
        materia: "Imagina a cena: você está planejando uma festa, o fim de semana daquele churrasco com os amigos ou quer simplesmente estocar as marmitas da semana em paz e, do nada, percebe que o freezer da geladeira já não dá conta do recado. E aí, a cabeça já começa a esquentar com uma dúvida: será que vale mais a pena investir em um freezer vertical ou horizontal? Pois é. Essa é uma daquelas decisões que parecem simples, mas que só quem viveu sabe o quanto importa. Até porque, escolher o formato ideal depende de tanta coisa, né? Tem o espaço disponível, o tipo de uso e até de como você gosta de organizar seus alimentos... E é justamente por isso que, hoje, o Blog Compra Certa está aqui para te ajudar a entender as diferenças entre freezer vertical ou horizontal, com todos os prós e contras de cada um e o que considerar antes da compra. Curtiu? Então, vem com a gente descobrir exatamente qual freezer faz mais sentido para sua casa ou até para aquele seu pequeno negócio que precisa de mais capacidade e economia.",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/6CqoHE6uGU6oBJDM8SHyNF/02e1723a7cf87467942f403e8873970c/shutterstock_2110328300.jpg",
    },
    {
        id: 20,
        slug: "Seminovos-guia-para-comprar-eletrodomesticos-com-100-de-seguranca",
        data: "27/02/2026",
        titulo: "Seminovos: guia para comprar eletrodomésticos com 100% de segurança",
        subtitulo: "Quando chega o momento de montar a casa, a expectativa cresce junto com a lista de eletrodomésticos.",
        materia: "Quando chega o momento de montar a casa, a expectativa cresce junto com a lista de eletrodomésticos. É geladeira, fogão, máquina de lavar, micro-ondas… tudo ao mesmo tempo, tudo importante, tudo indispensável, né? E ainda assim tem uma única coisa que não acompanha: o orçamento. Se você já passou por esse dilema, sabe como é. A gente pesquisa, compara, olha preço, vê promoção. Mas quer saber? Existe, sim, uma opção que ainda passa despercebida para muita gente: os eletrodomésticos seminovos. Eles são a ponte entre economia e qualidade, oferecendo modelos revisados, testados e com garantia, por um preço bem mais em conta. E para te mostrar porque essa é uma opção que você deve considerar, hoje nosso blog está daquele jeito: vamos juntos entender como funciona a oferta dos seminovos Compra Certa, conhecer o processo técnico que valida cada produto, a garantia que você tem e muito mais! Afinal, todo mundo quer e pode fazer escolhas mais econômicas, práticas e seguras, né? ",
        autor: "Compra certa",
        categoria: "Blog de Dicas",
        imagem: "https://images.ctfassets.net/qfxflpv0atz9/7fJzCJERCszGBt1ZlBw17Q/c35ac0a911bde9d48a11b3317e37bd5e/shutterstock_2644352963.jpg",
    },
]